# Configurações do site
# Edite os valores abaixo com suas informações pessoais.

title: Markdown Blog
email: ppablobr@gmail.com
description: >-
  Blog pessoal sobre inteligência artificial, engenharia de prompts, engenharia de contexto e experiências.
  Compartilhando o que aprendo no dia a dia.

baseurl: "/markdown" # subpath do repositório no GitHub Pages
url: "https://ppablobr.github.io" # URL base do GitHub Pages

github_username: ppablobr

# Configurações de build
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true
future: true
timezone: America/Sao_Paulo
