# Configurações do site
# Edite os valores abaixo com suas informações pessoais.

title: Mundo Markdown
email: ppablobr@gmail.com
description: >-
  Falo sobre inteligência artificial aplicada em gestão de projetos, implementação de IA em corporações e como fazer gestão de agentes.

baseurl: "/markdown" # subpath do repositório no GitHub Pages
url: "https://ppablobr.github.io" # URL base do GitHub Pages

github_username: ppablobr

# Configurações de build
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true
future: true
timezone: America/Sao_Paulo
